version: '3.1'

services:

  postgres:
    image: postgres:11-alpine
    restart: always
    env_file: .env
    volumes:
      - tonyandreapi:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - tonyandreredis:/data
    ports:
      - "6379:6379"

volumes:
  tonyandreapi:
  tonyandreredis: